title: Eduardo Bernardo
description: Data/Analytics Engineer | BI & Marketing Analytics | Pipelines, Modeling, Automation, Observability

# Tema (usando tema nativo do GitHub Pages)
theme: minima

# Suas informações
author:
  name: Eduardo Bernardo
  email: 

# URLs
url: "https://ebrndx.github.io"
baseurl: ""

# Configurações
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Excluir do build
exclude:
  - Gemfile
  - Gemfile.lock
